src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LocationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LocationId</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hardware__c.object
<CustomObject>
    <fields>
        <fullName>AssignedToEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assigned to employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvNo__c</fullName>
        <label>MB/SN/ServerTag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Hardware__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hardware</label>
    <nameField>
        <label>Hardware Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware</pluralLabel>
    <recordTypes>
        <fullName>Monitor</fullName>
        <active>true</active>
        <label>Monitor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Notebook</fullName>
        <active>true</active>
        <label>Notebook</label>
    </recordTypes>
    <recordTypes>
        <fullName>PC</fullName>
        <active>true</active>
        <label>PC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Server</fullName>
        <active>true</active>
        <label>Server</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserPermissions__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>UserPermissions</relationshipLabel>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserPermission</label>
    <nameField>
        <label>UserPermissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserPermissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MainInventoryDao.cls
/**
 * Created by Trainee 4 on 2/6/2018.
 */

public with sharing class MainInventoryDao {

    public List<Account> getAllEmployees() {
        return [
                SELECT id, Name, Type,LocationId__r.Name,LocationID__r.id, (
                        SELECT Name, id, RecordType.Name, InvNo__c
                        FROM Hardware__r
                        WHERE RecordType.developerName IN ('Server', ' Notebook', 'PC')
                )
                FROM Account
                ORDER BY Name DESC
        ];
    }

    public List<Hardware__c> getEmployeeMonitors(String idEmployee) {
        return [
                SELECT name,InvNo__c
                FROM Hardware__c
                WHERE AssignedToEmployee__r.id = :idEmployee
                AND RecordType.developerName = 'Monitor'
        ];
    }

    public List<Account> getEmployeesByLocations(List<String> locations) {
        return [
                SELECT id, Name, Type,LocationId__r.Name,LocationID__r.id, (
                        SELECT Name, id, RecordType.Name, InvNo__c
                        FROM Hardware__r
                        WHERE RecordType.developerName IN ('Server', ' Notebook', 'PC')
                )
                FROM Account
                WHERE LocationID__r.Name IN :locations
                ORDER BY Name DESC
        ];
    }

    public List<UserPermissions__c> getUserPermissionLocations(String userId) {
        return [
                SELECT Location__r.name
                FROM UserPermissions__c
                WHERE User__r.id = :userId
        ];
    }
    public List<Location__c> getAllLocationsNames() {
        return [
                SELECT name
                FROM Location__c
        ];
    }
}