src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LocationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LocationId</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hardware__c.object
<CustomObject>
    <fields>
        <fullName>AssignedToEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assigned to employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvNo__c</fullName>
        <label>MB/SN/ServerTag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Hardware__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hardware</label>
    <nameField>
        <label>Hardware Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserPermissions__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>UserPermissions</relationshipLabel>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserPermission</label>
    <nameField>
        <label>UserPermissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserPermissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MainInventoryService.cls
public with sharing class MainInventoryService {

    public MainInventoryDao dao { get; set; }

    public MainInventoryService() {
        dao = new MainInventoryDao();
    }

    public Set<String> generateCityesList() {
        Set<String> cities = new Set<String>();
        for (Location__c location : dao.getAllLocationsNames()) {
            cities.add(location.name);
        }
        return cities;
    }

    public Boolean isUserAdmin(String id) {
        for (UserPermissions__c userPermissions : dao.getUserPermissionLocations(id)) {
            if (userPermissions.Location__c == null) {
                return true;
            }
        }
        return false;
    }

    public List<EmployeeMainPageDto> getAllEmployees() {
        return extractEmployeesIntoDto(dao.getAllEmployees());
    }

    public List<EmployeeMainPageDto> getEmployeesByPermission(String userId) {
        List<UserPermissions__c> userLocations = dao.getUserPermissionLocations(userId);
        List<String> locationsNames = new List<String>();
        for (UserPermissions__c userPerm : userLocations) {
            locationsNames.add(userPerm.Location__r.name);
        }
        return extractEmployeesIntoDto(dao.getEmployeesByLocations(locationsNames));
    }

    public List<EmployeeMainPageDto> getEmployeesByLocations(List<String> locations) {
        return extractEmployeesIntoDto(dao.getEmployeesByLocations(locations));
    }

    private List<EmployeeMainPageDto> extractEmployeesIntoDto(List<Account> accounts) {
        List<EmployeeMainPageDto> dtos = new List<EmployeeMainPageDto>();
        for (Account account : accounts) {
            List<Hardware__c> monitors = dao.getEmployeeMonitors(account.id);
            dtos.add(new EmployeeMainPageDto.EmployeeMainPageDtoBuilder()
                    .setEmpId(account.id)
                    .setEmpName(account.name)
                    .setEmpType(account.Type)
                    .setLocationId(account.LocationId__r.id)
                    .setLocationName(account.LocationId__r.Name)
                    .setDeviceId(account.Hardware__r.size() == 0 ? '' : account.Hardware__r.get(0).id)
                    .setDeviceName(account.Hardware__r.size() == 0 ? '' : account.Hardware__r.get(0).Name)
                    .setDeviceType(account.Hardware__r.size() == 0 ? '' : account.Hardware__r.get(0).RecordType.Name)
                    .setInvNumber(account.Hardware__r.size() == 0 ? '' : account.Hardware__r.get(0).InvNo__c)
                    .setMonitors(monitors)
                    .build());
        }
        return dtos;
    }
}