src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ImageUrl__c</fullName>
        <label>ImageUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LocationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LocationId</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hardware__c.object
<CustomObject>
    <fields>
        <fullName>AssignedToEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assigned to employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ImageUrl__c</fullName>
        <label>ImageUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>InvNo__c</fullName>
        <label>MB/SN/ServerTag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Hardware__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hardware</label>
    <nameField>
        <label>Hardware Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserPermissions__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>UserPermissions</relationshipLabel>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserPermission</label>
    <nameField>
        <label>UserPermissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserPermissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeviceTableService.cls
/**
 * Created by Ar-Krav on 28.02.2018.
 */

public with sharing class DeviceTableService {

    public List<Location__c> getLocationUserAdmin(Id id){
        List<Location__c> loc = [SELECT name FROM Location__c
        WHERE Id in (SELECT Location__c FROM UserPermissions__c WHERE User__c = :id)];


        if (loc.get(0).name != null) {
            return loc;
        }
        else {
            return [SELECT name FROM Location__c];
        }
    }

    public ApexPages.StandardSetController getDevicesStandardSetController(List<Location__c> location, DeviceTableFilters filters){
        String query = 'SELECT imageUrl__c, Name, AssignedToEmployee__r.name, InvNo__c, RecordType.name, LocationID__c'+
                ' FROM Hardware__c'+
                ' WHERE Parent__c=null'+
                ' AND LocationID__c IN :locations' +
                ' AND name LIKE \'%' + filters.nameFilterValue + '%\'' + getOwnerFilterQuery(filters.ownerFilterValue) +
                ' AND InvNo__c LIKE \'%' + filters.seriaFilterValue + '%\''+
                ' AND RecordType.developerName LIKE \'%' + filters.typeFilterValue + '%\''+
                ' ORDER BY Name';
        return new ApexPages.StandardSetController(database.getQueryLocator(query));
    }

    private String getOwnerFilterQuery(String ownerFilterValue){
        return ownerFilterValue.equals('') ? ownerFilterValue : ' AND AssignedToEmployee__r.name LIKE \'%' + ownerFilterValue + '%\'';
    }
}