src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ImageFormula__c</fullName>
        <formula>IMAGE(ImageUrl__c,&quot;Not Available&quot;,100,100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ImageFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LocationId</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hardware__c.object
<CustomObject>
    <fields>
        <fullName>AssignedToEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assigned to employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageFormula__c</fullName>
        <formula>IMAGE(ImageUrl__c,&quot;Not Available&quot;,100,100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ImageFormula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvNo__c</fullName>
        <label>MB/SN/ServerTag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OS__c</fullName>
        <label>OS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Hardware__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hardware</label>
    <nameField>
        <label>Hardware Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware</pluralLabel>
    <recordTypes>
        <fullName>Monitor</fullName>
        <active>true</active>
        <label>Monitor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Notebook</fullName>
        <active>true</active>
        <label>Notebook</label>
    </recordTypes>
    <recordTypes>
        <fullName>PC</fullName>
        <active>true</active>
        <label>PC</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HardwareService.cls
/**
 * Created by Trainee 1 on 2/6/2018.
 */

public with sharing class HardwareService {

    private static final String MONITOR = 'Monitor';
    private static final String PC = 'Pc';
    private static final String NOTEBOOK = 'Notebook';

    public Account account { get; private set; }

    private List<Hardware__c> assignedHardware;

    private List<Hardware__c> emptyDevices;

    public HardwareService( Id accountId ) {
        account = getAccount( accountId );
        assignedHardware = getHardware( accountId );
        emptyDevices = getEmptyDevices( accountId );
    }

    private Account getAccount( Id accountId ) {
        return [
                SELECT  Id,
                        Name,
                        Type,
                        ImageFormula__c,
                        LocationId__c
                FROM Account
                WHERE Id = :accountId
                LIMIT 1
        ];
    }

    private List<Hardware__c> getHardware( Id accountId ) {
        return [
               SELECT  Id,
                       Parent__c,
                       Name,
                       RecordType.Name,
                       AssignedToEmployee__c,
                       InvNo__c,
                       OS__c,
               ( SELECT Id, Name, RecordType.Name FROM Hardware__r )
               FROM Hardware__c
               WHERE AssignedToEmployee__c =: accountId
       ];
    }

    private List<Hardware__c> getEmptyDevices( Id accountId ) {
        return [
                SELECT id,
                        RecordType.Name,
                        Name,
                        Description__c,
                        InvNo__c,
                        Cost__c,
                        LocationID__c,
                        OS__c,
                        Parent__c
                FROM HardWare__c
                WHERE Parent__c = null AND AssignedToEmployee__c = null AND LocationID__c =: account.LocationId__c ] ;
    }

    public Hardware__c getWorkstation() {

        Hardware__c worksatation = new Hardware__c();

        for ( Hardware__c hardware : assignedHardware ) {
            if ( hardware.RecordType.Name == PC || hardware.RecordType.Name == NOTEBOOK ) {
                worksatation = hardware;
            }
        }

        return worksatation;
    }

    public List<Hardware__c> getMonitors() {

        List<Hardware__c> monitors = new List<Hardware__c>();

        for (Hardware__c hardware : assignedHardware ) {
            if ( hardware.RecordType.Name == MONITOR ) {
                monitors.add(hardware);
            }
        }

        return monitors;
    }

    public List<Hardware__c> getPeriphery() {

        List<Hardware__c> periphery = new List<Hardware__c>();

        for (Hardware__c currentHardware :  assignedHardware) {
            if(currentHardware.RecordType.Name == PC || currentHardware.RecordType.Name == NOTEBOOK ){
                for (Hardware__c per : currentHardware.Hardware__r) {
                    periphery.add(per);
                }
            }
        }

        return periphery;
    }

    public List<Hardware__c> getEmptyPc(){

        List<Hardware__c> emptyPC = new List<Hardware__c>();

        for (Hardware__c hardware : emptyDevices ) {
            if ( hardware.RecordType.Name == PC || hardware.RecordType.Name == NOTEBOOK) {
                emptyPC.add(hardware);
            }
        }

        return emptyPC;
    }

    public List<Hardware__c> getEmptyMonitor(){

        List<Hardware__c> emptyMonitor = new List<Hardware__c>();

        for (Hardware__c hardware : emptyDevices ) {
            if ( hardware.RecordType.Name == MONITOR) {
                emptyMonitor.add(hardware);
            }
        }

        return emptyMonitor;
    }

    public void delCurrentPC() {
        Hardware__c currentPC = getWorkstation();
        currentPC.AssignedToEmployee__c = null;
        update currentPC;
    }

    public void delCurrentMonitor(Id currentMonitorId) {
        Hardware__c currentMon = new Hardware__c( Id = currentMonitorId, AssignedToEmployee__c = null );
        update currentMon;
    }

    public PageReference toPage(PageReference page, Map<String, String> params, Boolean doRedirect) {
        page.getParameters().putAll( params );
        page.setRedirect( doRedirect );
        return page;
    }
}