src/objects/Hardware__c.object
<CustomObject>
    <fields>
        <fullName>InvNo__c</fullName>
        <label>MB/SN/ServerTag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Hardware__c</referenceTo>
        <relationshipLabel>Hardware</relationshipLabel>
        <relationshipName>Hardware</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hardware</label>
    <nameField>
        <label>Hardware Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hardware</pluralLabel>
    <recordTypes>
        <fullName>CPU</fullName>
        <active>true</active>
        <label>CPU</label>
    </recordTypes>
    <recordTypes>
        <fullName>HDD</fullName>
        <active>true</active>
        <label>HDD</label>
    </recordTypes>
    <recordTypes>
        <fullName>Motherboard</fullName>
        <active>true</active>
        <label>Motherboard</label>
    </recordTypes>
    <recordTypes>
        <fullName>RAM</fullName>
        <active>true</active>
        <label>RAM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeviceConfigurationService.cls
/**
 * Created by Ar-Krav on 28.02.2018.
 */

public with sharing class DeviceConfigurationService {
    public List<Hardware__c> getDeviceConfigurationHardwares(Id id){
        List<String> allowedRecordTypes = new List<String> {'Motherboard','CPU','RAM','HDD'};

        return [SELECT Name, InvNo__c, RecordType.name, Parent__c
        FROM Hardware__c
        WHERE Parent__c=:id
        AND RecordType.developername IN :allowedRecordTypes
        ORDER BY RecordType.developerName];
    }
}