src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserPermissions__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>UserPermissions</relationshipLabel>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserPermissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserPermission</label>
    <nameField>
        <label>UserPermissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserPermissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestApexModel.cls
/**
 * Created by Ar-Krav on 28.02.2018.
 */

public with sharing class TestApexModel {

    public List<Location__c> getUserAdminLocations(Id id, Boolean isGlobalAdmin){
        if (isGlobalAdmin) {
            return [SELECT name FROM Location__c];
        }
        else {
            return getUserPermissedLocations(id);
        }
    }

    public Boolean isUSerGlobalAdmin(Id userId){
        return getUserPermissedLocations(userId).isEmpty();
    }

    private List<Location__c> getUserPermissedLocations(Id userId){
        return [SELECT name FROM Location__c
                WHERE Id in (SELECT Location__c FROM UserPermissions__c WHERE User__c = :userId)];
    }

}